//
//  AuthResult.cs
//  merchant_integration
//  
//  Created by Juan Pablo Yiguerimián on 10/25/16.
//  Copyright © 2016 ForceITS. All rights reserved.
//
//  The software code, programs, and documentation are the confidential and
//  proprietary information of ForceITS Corporation ("Confidential Information").
//  You shall not disclose such Confidential Information and shall use it only
//  in accordance with the terms of the license agreement you entered into
//  with ForceITS or one of its licensed distributors.
//
//  ForceITS MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
//  SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
//  PURPOSE, OR NON-INFRINGEMENT. ForceITS SHALL NOT BE LIABLE FOR ANY DAMAGES
//  SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
//  THIS SOFTWARE OR ITS DERIVATIVES.
//

namespace merchant_integration.Core.Payloads
{
    /// <summary>
    /// This class represents the response payload received when calling an Authentication method.
    /// </summary>
    public class AuthResult
    {

        /// <summary>
        /// Boolean value that indicates if authentication process was successful
        /// </summary>
        public bool auth { get; set; }

        /// <summary>
        /// If 'auth' is true, this attribute will have the token generated by Authentication process.
        /// It can be used to do payments
        /// </summary>
        public string tok { get; set; }

    }
}
